#!/bin/bash -e
# regenerate joomla secret key and mysql password

. /etc/default/inithooks

CONF=/var/www/joomla/configuration.php
PASSWORD=$(mcookie)

update_conf() {
    sed -i "/$1 =/s/= .*;/= $2;/" $CONF
}

update_conf 'public $secret' "'$(mcookie)'"

update_conf 'public $password' "'$PASSWORD'"
$INITHOOKS_PATH/bin/mysqlconf.py --user=joomla --pass="$PASSWORD"
systemctl restart apache2
